name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.ref_name	 }}
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: miantang3/datax_web:${{ github.ref_name	 }}
        repository: miantang3/datax_web
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true 
